@url_dev = http://localhost:3052/v1/api/upload
### upload image url
POST {{url_dev}}/product/url
Content-Type: application/json
x-api-key:c94ed4180d830515a1f26d01f41c26022686b2fa10aa050cfd33e2e0709358f3c2f8710087e17885c5dfd92c043df8200850649cba0780ca786fca0f55dd73a2
x-client-id:6553269ba21d0a07b0cd7108
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTUzMjY5YmEyMWQwYTA3YjBjZDcxMDgiLCJlbWFpbCI6InRoYWlkYWluaGFuQGdtYWlsLmNvbSIsImlhdCI6MTcwNjE1ODU1NywiZXhwIjoxNzA2MzMxMzU3fQ.fmhR4rGFFSoKCkpCHuTrtoYg1opK3YDXySH0s19jpqc

